---
- name: Ensure pip3 has been installed
  apt:
    name: python3-pip
    state: present

- name: S3cmd
  block:
  - name: "S3cmd - Install package"
    pip:
      name: s3cmd
      state: present
  - name: "S3cmd - Consigure credentials"
    template:
      src: s3cfg.j2
      dest: /root/.s3cfg
      mode: 0600
      backup: yes
  - name: "S3cmd - Ensure existence of directory"
    file:
      path: "{{ item.src }}"
      state: directory
      recurse: true
    with_items: "{{ s3_sync }}"
  - name: "S3cmd - Generate sync script"
    template:
      src: s3sync.j2
      dest: /usr/local/bin/s3sync
      mode: 0755
# Does not work more
#  - name: "S3cmd - Check script"
#    command: "/usr/local/bin/s3cmd --dry-run"
#    register: s3_test
#  - debug:
#      msg: "{{ s3_test.stdout }}"

  when:
  - s3_access_key is defined
  - s3_secret_key is defined

- name: Deploy database backup script
  template:
    src: backup-db.sh
    dest: /usr/local/bin/backup-db
    mode: 0755
  when:
  - services["mysql"] is defined
  - backup_db_script == true

- name: Deploy files backup script
  template:
    src: backup-fs.sh
    dest: /usr/local/bin/backup-fs
    mode: 0755
  when:
  - backup_fs_script == true

