---
- block:
  - name: "S4cmd - Install package"
    apt:
      name: s4cmd
      state: present

  - name: "S4cmd - Consigure credentials"
    template:
      src: s3cfg.j2
      dest: /root/.s3cfg
      mode: 0600
      backup: yes

  - name: Configure backup jobs
    include_tasks: backup_jobs.yml
    loop: "{{ s3_backup_jobs }}"

  when:
  - s3_access_key is defined
  - s3_secret_key is defined

- name: Database backup
  include: backup_db.yml
  when:
  - services["mysql"] is defined
  - backup_db_script == true


